#!/bin/bash
clear
printf "Este script permite la actualización de la suite Adobe CC 2015.\n"
echo ""
echo "Presione ENTER para continuar, de lo contrario cierra esta ventana."
read ok
echo "Por ingrese la contraseña de Administrador..."
echo ""
sudo rm -rf "/Library/Application Support/Adobe/AAMUpdaterInventory/1.0/AdobeUpdaterAdminPrefs.dat"
echo "El proceso ha finalizado"
echo "Puede reintentar la actualización."
echo "@andriuzha"
exit 0
